Repository mo-moim/momoim-FE, pull requests merged in 2024-12, with the labels that each got.

#5 Feature/svgr
  next.config.js
  package-lock.json
  package.json
Labels: ⚙️ setting

#7 chore: provider 셋팅 및 테스트 코드
  package.json
  src/app/(main)/page.tsx
  src/app/layout.tsx
  src/lib/Instance.tsx
  src/lib/TanStackProvider.tsx
  src/styles/globals.css
  src/tests/page.test.tsx
Labels: ⚙️ setting

#9 chore: 폰트, shadcn 셋팅
  .eslintrc.json
  components.json
  package-lock.json
  package.json
  src/app/layout.tsx
  src/assets/fonts/GeistMonoVF.woff
  src/assets/fonts/GeistVF.woff
  src/assets/fonts/PretendardVariable.woff2
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/popover.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/select.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/use-toast.ts
  src/lib/utils.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: 🎨 design, ⚙️ setting

#14 feat: 레이아웃 및 GNB 기본 구조 구현
  src/app/(main)/page.tsx
  src/app/_component/AuthButtons.tsx
  src/app/_component/Header.tsx
  src/app/layout.tsx
  src/assets/svg/logo.svg
Labels: ✨ feature

#18 feat: 태그 컴포넌트 구현
  package-lock.json
  package.json
  src/components/common/Tags.tsx
  src/lib/sectionSlider.ts
  tailwind.config.ts
Labels: ✨ feature

#19 feature: modal 컴포넌트 구현
  package-lock.json
  package.json
  src/components/common/.keep
  src/components/common/Modal.tsx
  src/components/ui/dialog.tsx
  src/hooks/.keep
  src/tests/.keep
  src/types/.keep
  src/types/common/modal.ts
  tailwind.config.ts
Labels: ✨ feature

#20 chore: 중간 배포 점검
  .eslintrc.json
  .github/workflows/test-coverage.yml
  .husky/commit-msg
  codecov.yml
  components.json
  next.config.js
  package-lock.json
  package.json
  src/api/auth.ts
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/gatherings/[id]/page.tsx
  src/app/(main)/liked/page.tsx
  src/app/(main)/mypage/page.tsx
  src/app/(main)/page.tsx
  src/app/(main)/reviews/page.tsx
  src/app/_component/AuthButtons.tsx
  src/app/_component/Header.tsx
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/fonts/PretendardVariable.woff2
  src/assets/svg/logo.svg
  src/components/common/Modal.tsx
  src/components/common/Tabs.tsx
  src/components/common/Tags.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/dialog.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/popover.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/select.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/constants/api.ts
  src/hooks/use-toast.ts
  src/lib/Instance.tsx
  src/lib/TanStackProvider.tsx
  src/lib/sectionSlider.ts
  src/lib/utils.ts
  src/store/.keep
  src/styles/globals.css
  src/tests/page.test.tsx
  src/types/common/modal.ts
  tailwind.config.ts
Labels: 💻 deploy

#22 test: modal 컴포넌트 테스트 코드 작성
  src/app/(main)/gatherings/[id]/community/page.tsx
  src/app/(main)/gatherings/[id]/description/page.tsx
  src/app/(main)/gatherings/[id]/reviews/page.tsx
  src/tests/modal.test.tsx
  src/tests/page.test.tsx
  src/types/common/modal.ts
Labels: ✅ test

#24 Feature/sign up
  package-lock.json
  package.json
  src/app/(auth)/_component/AuthLayout.tsx
  src/app/(auth)/signup/_component/SelectButton.tsx
  src/app/(auth)/signup/_component/StepIndicator.tsx
  src/app/(auth)/signup/_component/StepOne.tsx
  src/app/(auth)/signup/_component/StepTwo.tsx
  src/app/(auth)/signup/page.tsx
  src/app/_component/Header.tsx
  src/assets/svg/check-icon.svg
  src/components/common/FormFieldWrapper.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/constants/options.ts
  src/lib/Instance.tsx
  src/lib/axios.ts
  src/schemas/auth.ts
  src/types/auth.ts
Labels: ✨ feature

#25 feat: 회원가입 API 연동 및 UX/UI 개선
  src/api/auth.ts
  src/app/(auth)/signup/_component/SelectButton.tsx
  src/app/(auth)/signup/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/assets/svg/check-icon.svg
  src/components/ui/toast.tsx
  src/constants/api.ts
  src/lib/TanStackProvider.tsx
  src/queries/auth/useSignUp.ts
  tailwind.config.ts
Labels: ✨ feature, 🎨 design, ⚙️ setting

#32 test: 회원가입 테스트 코드 작성
  package-lock.json
  package.json
  src/app/(auth)/signup/_component/SelectButton.test.tsx
  src/app/(auth)/signup/_component/StepIndicator.test.tsx
  src/app/(auth)/signup/_component/StepOne.test.tsx
  src/app/(auth)/signup/_component/StepOne.tsx
  src/app/(auth)/signup/_component/StepTwo.test.tsx
  src/app/(auth)/signup/page.tsx
  src/components/common/FormFieldWrapper.tsx
  src/constants/formLabels.ts
  src/constants/messages.ts
  src/schemas/auth.ts
Labels: ✅ test

#38 feat: 로그인 페이지 개발
  src/api/auth.ts
  src/app/(auth)/_component/AuthLayout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/_component/StepOne.tsx
  src/lib/axios.ts
  src/queries/auth/useLogin.ts
  src/schemas/auth.ts
  src/types/auth.ts
Labels: ✨ feature

#30 feat: 모임데이터 카드 컴포넌트 구현
  next.config.js
  src/assets/svg/default-profile.svg
  src/assets/svg/geography_map_solid.svg
  src/assets/svg/logo.svg
  src/assets/svg/person.svg
  src/components/common/Chip.tsx
  src/components/common/Heart.tsx
  src/components/common/ProgressBar.tsx
  src/components/common/cards/DetailCard.tsx
  src/components/common/cards/MoimCard.tsx
  src/lib/dateFormatter.ts
  src/lib/leftTimeGenerator.ts
  src/styles/globals.css
  src/types/common/gatheringContent.ts
  src/types/common/members.ts
  tailwind.config.ts
Labels: ✨ feature

#39 deploy: main 2차 병합
  next.config.js
  package-lock.json
  package.json
  src/api/auth.ts
  src/app/(auth)/_component/AuthLayout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/_component/SelectButton.test.tsx
  src/app/(auth)/signup/_component/SelectButton.tsx
  src/app/(auth)/signup/_component/StepIndicator.test.tsx
  src/app/(auth)/signup/_component/StepIndicator.tsx
  src/app/(auth)/signup/_component/StepOne.test.tsx
  src/app/(auth)/signup/_component/StepOne.tsx
  src/app/(auth)/signup/_component/StepTwo.test.tsx
  src/app/(auth)/signup/_component/StepTwo.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/gatherings/[id]/community/page.tsx
  src/app/(main)/gatherings/[id]/description/page.tsx
  src/app/(main)/gatherings/[id]/reviews/page.tsx
  src/app/_component/Header.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/assets/svg/default-profile.svg
  src/assets/svg/geography_map_solid.svg
  src/assets/svg/logo.svg
  src/assets/svg/person.svg
  src/components/common/Chip.tsx
  src/components/common/FormFieldWrapper.tsx
  src/components/common/Heart.tsx
  src/components/common/Modal.tsx
  src/components/common/ProgressBar.tsx
  src/components/common/cards/DetailCard.tsx
  src/components/common/cards/MoimCard.tsx
  src/components/common/modal/Modal.test.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/select/Select.test.tsx
  src/components/common/select/Select.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/select.tsx
  src/components/ui/toast.tsx
  src/constants/api.ts
  src/constants/formLabels.ts
  src/constants/messages.ts
  src/constants/options.ts
  src/lib/Instance.tsx
  src/lib/TanStackProvider.tsx
  src/lib/axios.ts
  src/lib/dateFormatter.ts
  src/lib/leftTimeGenerator.ts
  src/queries/auth/useLogin.ts
  src/queries/auth/useSignUp.ts
  src/schemas/auth.ts
  src/styles/globals.css
  src/tests/page.test.tsx
  src/types/auth.ts
  src/types/common/gatheringContent.ts
  src/types/common/members.ts
  src/types/common/modal.ts
  tailwind.config.ts
Labels: 💻 deploy

#41 feat: GNB 유저 프로필 기능 추가
  src/api/user.ts
  src/app/(auth)/_component/AuthLayout.tsx
  src/app/_component/Header.tsx
  src/app/_component/ProfileButton.tsx
  src/assets/svg/logo.svg
  src/queries/auth/useLogin.ts
  src/queries/auth/useUser.ts
  src/types/auth.ts
  tailwind.config.ts
Labels: ✨ feature

#43 feat: 모임 페이지 생성 및 카테고리 기능 추가
  src/app/(main)/[category]/page.tsx
  src/app/(main)/_component/MoimPage.tsx
  src/app/(main)/page.tsx
  src/components/common/Tabs.tsx
  src/components/common/Tags.tsx
  src/components/ui/button.tsx
  src/constants/options.ts
  src/styles/globals.css
Labels: ✨ feature

#44 deploy: main 병합
  src/api/user.ts
  src/app/(auth)/_component/AuthLayout.tsx
  src/app/(main)/[category]/page.tsx
  src/app/(main)/_component/MoimPage.tsx
  src/app/(main)/page.tsx
  src/app/_component/Header.tsx
  src/app/_component/ProfileButton.tsx
  src/assets/svg/logo.svg
  src/components/common/Tabs.tsx
  src/components/common/Tags.tsx
  src/components/ui/button.tsx
  src/constants/options.ts
  src/queries/auth/useLogin.ts
  src/queries/auth/useUser.ts
  src/styles/globals.css
  src/types/auth.ts
  tailwind.config.ts
Labels: 💻 deploy

#45 feature: 모임 생성 페이지 및 컴포넌트 수정 사항
  next.config.js
  package-lock.json
  package.json
  src/api/gatherings.ts
  src/api/imageFile.ts
  src/app/(main)/gatherings/[id]/_component/GatheringDeteil.tsx
  src/app/(main)/gatherings/create/_component/AddressInput.tsx
  src/app/(main)/gatherings/create/_component/Category.tsx
  src/app/(main)/gatherings/create/_component/DateTimePicker.tsx
  src/app/(main)/gatherings/create/_component/FormOnlineAddress.tsx
  src/app/(main)/gatherings/create/_component/FormTypeButton.tsx
  src/app/(main)/gatherings/create/_component/GatheringForm.tsx
  src/app/(main)/gatherings/create/_component/GatheringUploadImage.tsx
  src/app/(main)/gatherings/create/_component/SubCategoryButton.tsx
  src/app/(main)/gatherings/create/page.tsx
  src/app/_component/BackButton.tsx
  src/assets/images/thumbnail.png
  src/components/common/FormFieldWrapper.tsx
  src/components/common/modal/Modal.test.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/select/Select.test.tsx
  src/components/common/select/Select.tsx
  src/components/ui/calendar.tsx
  src/constants/options.ts
  src/lib/inputDataFormat.ts
  src/queries/gathering/useCreate.ts
  src/schemas/gatheringCreate.ts
  src/store/.keep
  src/store/modalStore.ts
  src/styles/globals.css
  src/types/category.ts
  src/types/common/formFieldprops.ts
Labels: ✨ feature, 🛠️ refactor

#47 feat: 모임 목록 조회 기능 개발
  .env
  .gitignore
  src/api/gatherings/getMoimList.ts
  src/app/(main)/[category]/page.tsx
  src/app/(main)/_component/Filters.tsx
  src/app/(main)/_component/MoimGrid.tsx
  src/app/(main)/_component/MoimPage.tsx
  src/app/(main)/page.tsx
  src/components/common/EmptyState.tsx
  src/components/common/Tags.tsx
  src/constants/config.ts
  src/constants/gatherings.ts
  src/constants/options.ts
  src/hooks/useIntersectionObserver.ts
  src/queries/gatherings/getMoimListQuery.ts
  src/queries/gatherings/useMoimList.ts
  src/types/gathering.ts
Labels: ✨ feature, ⚙️ setting

#48 feature: 생성 페이지 editor 적용
  .github/ISSUE_TEMPLATE/bug-template.yml
  .github/ISSUE_TEMPLATE/feature-template.yml
  .github/workflows/test-coverage.yml
  package-lock.json
  package.json
  src/app/(main)/gatherings/create/_component/GatheringForm.tsx
  src/app/(main)/gatherings/create/_component/GatheringUploadImage.tsx
  src/components/common/EditorWrapper.tsx
  src/components/common/ToastEditor.tsx
  src/components/ui/skeleton.tsx
  src/styles/globals.css
Labels: ✨ feature

#49 feat: 모임 만들기 버튼 생성
  src/app/(main)/_component/MoimGrid.tsx
  src/app/(main)/liked/page.tsx
  src/app/(main)/reviews/page.tsx
  src/app/_component/AuthSection.tsx
  src/app/_component/CreateMoimButton.tsx
  src/app/_component/Header.tsx
  src/app/layout.tsx
  src/components/common/EmptyState.tsx
  src/lib/TanStackProvider.tsx
  src/queries/auth/useUser.ts
Labels: 🏃‍♂️ troubleshooting, ✨ feature

#52 fix: 모임 생성 시 썸네일 이미지
  src/app/(main)/gatherings/create/_component/AddressInput.test.tsx
  src/app/(main)/gatherings/create/_component/FormOnlineAddress.test.tsx
  src/app/(main)/gatherings/create/_component/FormTypeButton.test.tsx
  src/app/(main)/gatherings/create/_component/GatheringUploadImage.test.tsx
  src/app/(main)/gatherings/create/_component/GatheringUploadImage.tsx
  src/schemas/gatheringCreate.ts
  src/types/category.ts
  src/types/common/formFieldprops.ts
Labels: ✅ test, 🛠️ refactor

#53 feat: 닉네임 및 이메일 중복 확인 로직 추가 및 관련 테스트 작성
  src/api/auth/auth.ts
  src/api/auth/check.ts
  src/api/auth/user.ts
  src/app/(auth)/signup/_component/DuplicateCheckField.test.tsx
  src/app/(auth)/signup/_component/DuplicateCheckField.tsx
  src/app/(auth)/signup/_component/PasswordField.test.tsx
  src/app/(auth)/signup/_component/PasswordField.tsx
  src/app/(auth)/signup/_component/SelectButton.tsx
  src/app/(auth)/signup/_component/StepOne.test.tsx
  src/app/(auth)/signup/_component/StepOne.tsx
  src/app/(auth)/signup/_component/StepTwo.test.tsx
  src/app/(auth)/signup/hooks/useDuplicateCheck.ts
  src/app/(auth)/signup/hooks/useSignUpForm.ts
  src/app/(auth)/signup/page.tsx
  src/app/(main)/_component/Filters.tsx
  src/app/_component/CreateMoimButton.tsx
  src/components/ui/button.tsx
  src/constants/formLabels.ts
  src/constants/messages.ts
  src/queries/auth/useCheckDuplicateValue.ts
  src/queries/auth/useLogin.ts
  src/queries/auth/useSignUp.ts
  src/queries/auth/useUser.ts
  src/types/auth.ts
Labels: ✨ feature, ✅ test

#50 feat: 마이페이지 - 나의 일정 / 나의 모임 / 나의 리뷰 페이지 구현
  next.config.js
  src/api/like.ts
  src/api/moim.ts
  src/api/review.ts
  src/api/schedule.ts
  src/app/(main)/mypage/_components/Calendar.tsx
  src/app/(main)/mypage/_components/ClientRedirectHandler.tsx
  src/app/(main)/mypage/_components/EmptyStatePicker.tsx
  src/app/(main)/mypage/_components/MypageTabs.tsx
  src/app/(main)/mypage/_components/ProfileBox.tsx
  src/app/(main)/mypage/_components/ProfileEdit.tsx
  src/app/(main)/mypage/_components/RatingSection.tsx
  src/app/(main)/mypage/_components/ReviewPostSection.tsx
  src/app/(main)/mypage/_components/ScheduleBox.tsx
  src/app/(main)/mypage/_components/ScheduleCard.tsx
  src/app/(main)/mypage/_components/UnreviewedCard.tsx
  src/app/(main)/mypage/gatherings/page.tsx
  src/app/(main)/mypage/layout.tsx
  src/app/(main)/mypage/page.tsx
  src/app/(main)/mypage/reviews/page.tsx
  src/app/(main)/mypage/schedules/page.tsx
  src/assets/svg/default-image.svg
  src/assets/svg/empty-star.svg
  src/assets/svg/geography_map_solid.svg
  src/assets/svg/half-star.svg
  src/assets/svg/star.svg
  src/components/common/Chip.tsx
  src/components/common/Chips.tsx
  src/components/common/Heart.tsx
  src/components/common/Star.tsx
  src/components/common/Tabs.tsx
  src/components/common/TopButton.tsx
  src/components/common/cards/DetailCard.tsx
  src/components/common/cards/MoimCard.tsx
  src/components/common/cards/ReviewCard.tsx
  src/lib/dateFormatter.ts
  src/lib/getLabel.ts
  src/lib/imageValidChecker.ts
  src/queries/mypage/useGathering.ts
  src/queries/mypage/useLike.ts
  src/queries/mypage/useReview.ts
  src/queries/mypage/useSchedule.ts
  src/types/common/chip.ts
  src/types/common/gatheringContent.ts
  src/types/common/scheduleData.ts
  src/types/pagination.ts
  tailwind.config.ts
Labels: ✨ feature

#54 feat: 생성 Form 에디터 변경 및 컴포넌트 수정
  .github/workflows/test-coverage.yml
  package-lock.json
  package.json
  src/app/(main)/gatherings/create/_component/AddressInput.test.tsx
  src/app/(main)/gatherings/create/_component/AddressInput.tsx
  src/app/(main)/gatherings/create/_component/Category.tsx
  src/app/(main)/gatherings/create/_component/GatheringForm.tsx
  src/app/(main)/gatherings/create/_component/SubCategoryButton.test.tsx
  src/app/(main)/gatherings/create/_component/SubCategoryButton.tsx
  src/components/common/EditorWrapper.tsx
  src/components/common/ToastEditor.tsx
  src/components/common/editor/Tiptab.tsx
  src/components/common/editor/TiptabImage.tsx
  src/components/common/editor/TiptabLink.tsx
  src/components/common/editor/Toolbar.tsx
  src/components/common/modal/Modal.test.tsx
  src/components/common/modal/Modal.tsx
  src/queries/mypage/useReview.ts
  src/store/.keep
  src/store/modalStore.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ feature, ✅ test, 🛠️ refactor

#55 Feature/moimlist
  src/app/(main)/[category]/_component/Filters.tsx
  src/app/(main)/[category]/_component/MoimGrid.tsx
  src/app/(main)/[category]/_component/MoimPage.tsx
  src/app/(main)/[category]/_component/skeletons/MoimCardSkeleton.tsx
  src/app/(main)/[category]/_component/skeletons/MoimGridSkeleton.tsx
  src/app/(main)/[category]/page.tsx
  src/app/(main)/_component/MoimGrid.tsx
  src/app/_component/ProfileButton.tsx
  src/components/common/Heart.tsx
  src/components/common/Tabs.tsx
  src/components/common/cards/MoimCard.tsx
  src/constants/config.ts
  src/queries/gatherings/useMoimList.ts
Labels: ✨ feature, 🎨 design

#59 feat: footer 컴포넌트 추가 및 스타일 개선
  src/app/_component/Footer.tsx
  src/app/_component/Header.tsx
  src/app/layout.tsx
  src/styles/globals.css
Labels: ✨ feature, 🎨 design
