Repository mo-moim/momoim-FE, pull requests merged in 2025-01, with the labels that each got.

#63 feat: DatePicker 컴포넌트 추가
  src/app/(main)/[category]/_component/Filters.tsx
  src/app/(main)/gatherings/create/_component/DateTimePicker.tsx
  src/components/common/DatePicker.tsx
  src/components/common/cards/MoimCard.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
Labels: ✨ feature

#60 feat: 마이페이지 구현
  src/api/auth/user.ts
  src/api/schedule.ts
  src/app/(main)/mypage/_components/ClientRedirectHandler.tsx
  src/app/(main)/mypage/_components/MyPageCalendar.tsx
  src/app/(main)/mypage/_components/ProfileBox.tsx
  src/app/(main)/mypage/_components/ProfileEdit.tsx
  src/app/(main)/mypage/_components/RatingSection.tsx
  src/app/(main)/mypage/_components/RegionButtons.tsx
  src/app/(main)/mypage/_components/ReviewPostSection.tsx
  src/app/(main)/mypage/_components/ScheduleCard.tsx
  src/app/(main)/mypage/_components/UnreviewedCard.tsx
  src/app/(main)/mypage/_components/UpperPart.tsx
  src/app/(main)/mypage/_components/skeletons/MyGatheringsSkeleton.tsx
  src/app/(main)/mypage/_components/skeletons/MyPageTagsSkeleton.tsx
  src/app/(main)/mypage/_components/skeletons/MyReviewsSkeleton.tsx
  src/app/(main)/mypage/_components/skeletons/MySchedulesSkeleton.tsx
  src/app/(main)/mypage/_components/skeletons/UpperPartSkeleton.tsx
  src/app/(main)/mypage/gatherings/page.tsx
  src/app/(main)/mypage/layout.tsx
  src/app/(main)/mypage/reviews/page.tsx
  src/app/(main)/mypage/schedules/page.tsx
  src/components/common/FormFieldWrapper.tsx
  src/components/common/Heart.tsx
  src/components/common/cards/MoimCard.tsx
  src/components/common/cards/ReviewCard.tsx
  src/constants/profile.ts
  src/queries/auth/useEditUser.tsx
  src/queries/mypage/useLike.ts
  src/queries/mypage/useReview.ts
  src/queries/mypage/useSchedule.ts
  src/schemas/profileEdit.ts
  src/schemas/reviewPost.ts
  src/types/profile.ts
  src/types/review.ts
Labels: ✨ feature

#61 feat: 모임 상세 페이지
  .github/ISSUE_TEMPLATE/bug-template.yml
  package-lock.json
  package.json
  src/api/gatherings.ts
  src/app/(main)/gatherings/[id]/_component/DetailButton.tsx
  src/app/(main)/gatherings/[id]/_component/DetailCardMember.tsx
  src/app/(main)/gatherings/[id]/_component/DetailCheckTime.tsx
  src/app/(main)/gatherings/[id]/_component/DetailPageTab.tsx
  src/app/(main)/gatherings/[id]/_component/DetailViewer.tsx
  src/app/(main)/gatherings/[id]/_component/GatheringCheckTime.tsx
  src/app/(main)/gatherings/[id]/_component/GatheringDeteil.tsx
  src/app/(main)/gatherings/[id]/_component/KaKaoMap.tsx
  src/app/(main)/gatherings/[id]/_component/MapSkeleton.tsx
  src/app/(main)/gatherings/[id]/_component/MemberModal.tsx
  src/app/(main)/gatherings/[id]/layout.tsx
  src/app/(main)/gatherings/[id]/page.tsx
  src/app/(main)/gatherings/create/_component/AddressInput.tsx
  src/app/(main)/gatherings/create/_component/DateTimePicker.tsx
  src/app/(main)/gatherings/create/_component/GatheringForm.tsx
  src/app/_component/BackButton.tsx
  src/components/common/DatePicker.tsx
  src/components/common/cards/DetailCard.tsx
  src/components/common/editor/Tiptab.tsx
  src/components/common/editor/TiptabImage.tsx
  src/components/common/editor/TiptabLink.tsx
  src/components/common/modal/Modal.tsx
  src/components/ui/dialog.tsx
  src/constants/gatheringDetailTabs.ts
  src/lib/getLabel.ts
  src/queries/gatherings-workspace/useGatheringCreate.ts
  src/queries/gatherings-workspace/useGatheringDelete.ts
  src/queries/gatherings-workspace/useGatheringDetail.ts
  src/queries/gatherings-workspace/useGatheringMemberDelete.ts
  src/queries/gatherings-workspace/useGatheringPatch.ts
  src/queries/gatherings/useGatheringJoin.ts
  src/queries/gatherings/useGatheringJoinCancel.ts
  src/schemas/gatheringCreate.ts
  src/styles/globals.css
  src/types/common/gatheringContent.ts
  tsconfig.json
Labels: ✨ feature, 🎨 design

#65 feat: 모임 상세 수정 및 리뷰
  src/api/gatherings.ts
  src/api/review.ts
  src/app/(main)/gatherings/[id]/_component/DetailButton.tsx
  src/app/(main)/gatherings/[id]/_component/DetailCheckTime.tsx
  src/app/(main)/gatherings/[id]/_component/GatheringDeteil.tsx
  src/app/(main)/gatherings/[id]/_component/KaKaoMap.tsx
  src/app/(main)/gatherings/[id]/_component/MemberModal.tsx
  src/app/(main)/gatherings/[id]/community/page.tsx
  src/app/(main)/gatherings/[id]/description/page.tsx
  src/app/(main)/gatherings/[id]/layout.tsx
  src/app/(main)/gatherings/[id]/page.tsx
  src/app/(main)/gatherings/[id]/reviews/_component/ReviewAverage.tsx
  src/app/(main)/gatherings/[id]/reviews/_component/ReviewList.tsx
  src/app/(main)/gatherings/[id]/reviews/page.tsx
  src/app/(main)/gatherings/_component/FormLayout.tsx
  src/app/(main)/gatherings/create/_component/AddressInput.tsx
  src/app/(main)/gatherings/create/_component/FormOnlineAddress.tsx
  src/app/(main)/gatherings/create/_component/GatheringForm.tsx
  src/app/(main)/gatherings/create/page.tsx
  src/app/(main)/gatherings/edit/GatheringEdit.tsx
  src/app/(main)/gatherings/edit/page.tsx
  src/app/_component/BackButton.tsx
  src/assets/images/makrer.png
  src/components/common/ProgressBar.tsx
  src/components/common/cards/DetailCard.tsx
  src/components/common/cards/ReviewCard.tsx
  src/components/common/select/Select.tsx
  src/hooks/useLoading.ts
  src/queries/gatherings-workspace/useGatheringDelete.ts
  src/queries/gatherings-workspace/useGatheringDetail.ts
  src/queries/gatherings-workspace/useGatheringPatch.ts
  src/queries/mypage/useReview.ts
  src/schemas/gatheringCreate.ts
  src/types/category.ts
  src/types/review.ts
Labels: ✨ feature

#69 feat: 미들웨어 추가 및 인증 관련 기능 구현
  .gitignore
  package.json
  src/api/auth/auth.ts
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/_component/ProfileButton.tsx
  src/lib/TanStackProvider.tsx
  src/lib/axios.ts
  src/middleware.ts
  src/queries/auth/useLogin.ts
  src/queries/auth/useLogout.ts
Labels: ✨ feature

#71 fix: 맴버 리스트 및 인원에 따른 모집 마감 수정
  src/app/(main)/gatherings/[id]/_component/DetailButton.tsx
  src/app/(main)/gatherings/[id]/_component/DetailCardMember.tsx
  src/app/(main)/gatherings/[id]/_component/DetailCheckTime.tsx
  src/app/(main)/gatherings/edit/_component/GatheringEdit.tsx
  src/app/(main)/gatherings/edit/page.tsx
  src/app/not-found.tsx
  src/assets/images/notFoundPage.png
  src/components/common/cards/DetailCard.tsx
  src/types/common/gatheringContent.ts
Labels: 🛠️ refactor

#72 deploy: main 배포 병합
  .gitignore
  package.json
  src/api/auth/auth.ts
  src/api/gatherings.ts
  src/api/review.ts
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/gatherings/[id]/_component/DetailButton.tsx
  src/app/(main)/gatherings/[id]/_component/DetailCardMember.tsx
  src/app/(main)/gatherings/[id]/_component/DetailCheckTime.tsx
  src/app/(main)/gatherings/[id]/_component/GatheringDeteil.tsx
  src/app/(main)/gatherings/[id]/_component/KaKaoMap.tsx
  src/app/(main)/gatherings/[id]/_component/MemberModal.tsx
  src/app/(main)/gatherings/[id]/community/page.tsx
  src/app/(main)/gatherings/[id]/description/page.tsx
  src/app/(main)/gatherings/[id]/layout.tsx
  src/app/(main)/gatherings/[id]/page.tsx
  src/app/(main)/gatherings/[id]/reviews/_component/ReviewAverage.tsx
  src/app/(main)/gatherings/[id]/reviews/_component/ReviewList.tsx
  src/app/(main)/gatherings/[id]/reviews/page.tsx
  src/app/(main)/gatherings/_component/FormLayout.tsx
  src/app/(main)/gatherings/create/_component/AddressInput.tsx
  src/app/(main)/gatherings/create/_component/FormOnlineAddress.tsx
  src/app/(main)/gatherings/create/_component/GatheringForm.tsx
  src/app/(main)/gatherings/create/page.tsx
  src/app/(main)/gatherings/edit/_component/GatheringEdit.tsx
  src/app/(main)/gatherings/edit/page.tsx
  src/app/_component/BackButton.tsx
  src/app/_component/ProfileButton.tsx
  src/app/not-found.tsx
  src/assets/images/makrer.png
  src/assets/images/notFoundPage.png
  src/components/common/ProgressBar.tsx
  src/components/common/cards/DetailCard.tsx
  src/components/common/cards/ReviewCard.tsx
  src/components/common/select/Select.tsx
  src/hooks/useLoading.ts
  src/lib/TanStackProvider.tsx
  src/lib/axios.ts
  src/middleware.ts
  src/queries/auth/useLogin.ts
  src/queries/auth/useLogout.ts
  src/queries/gatherings-workspace/useGatheringDelete.ts
  src/queries/gatherings-workspace/useGatheringDetail.ts
  src/queries/gatherings-workspace/useGatheringPatch.ts
  src/queries/mypage/useReview.ts
  src/schemas/gatheringCreate.ts
  src/types/category.ts
  src/types/common/gatheringContent.ts
  src/types/review.ts
Labels: 💻 deploy

#70 feat: 탭 마우스엔터시 프리로드 추가
  src/api/auth/user.ts
  src/app/(main)/mypage/_components/MypageTabs.tsx
  src/app/(main)/mypage/_components/ProfileBox.tsx
  src/app/(main)/mypage/_components/UpperPart.tsx
  src/app/(main)/mypage/_components/skeletons/MyPageProfileBoxSkeleton.tsx
  src/app/(main)/mypage/gatherings/page.tsx
  src/app/(main)/mypage/layout.tsx
  src/app/(main)/mypage/reviews/page.tsx
  src/app/(main)/mypage/schedules/page.tsx
  src/components/common/Tabs.tsx
  src/components/common/Tags.tsx
  src/components/common/cards/MoimCard.tsx
  src/middleware.ts
  src/queries/mypage/useGathering.ts
  src/queries/mypage/useReview.ts
  src/queries/mypage/useSchedule.ts
Labels: ✨ feature, 🛠️ refactor

#74 fix: 피드백 및 보완 사항 추가
  src/app/(main)/gatherings/[id]/_component/DetailPageTab.tsx
  src/app/(main)/gatherings/[id]/reviews/_component/ReviewAverage.tsx
  src/app/(main)/gatherings/create/_component/AddressInput.test.tsx
  src/app/(main)/gatherings/create/_component/FormOnlineAddress.test.tsx
  src/app/(main)/gatherings/create/_component/GatheringForm.tsx
  src/app/(main)/gatherings/create/_component/GatheringUploadImage.test.tsx
  src/app/(main)/gatherings/create/_component/SubCategoryButton.test.tsx
  src/app/(main)/gatherings/create/_component/SubCategoryButton.tsx
  src/app/(main)/gatherings/create/page.tsx
  src/app/(main)/gatherings/edit/_component/GatheringEdit.tsx
  src/components/common/ProgressBar.tsx
  src/components/common/editor/Tiptab.tsx
  src/components/common/modal/Modal.tsx
  src/constants/scoreMapping.ts
  src/queries/gatherings-workspace/useGatheringCreate.ts
  src/queries/gatherings-workspace/useGatheringDelete.ts
  src/queries/gatherings-workspace/useGatheringPatch.ts
  src/schemas/gatheringCreate.ts
Labels: ✨ feature, 🛠️ refactor

#75 deploy: main 배포 병합
  src/api/auth/user.ts
  src/app/(main)/gatherings/[id]/_component/DetailPageTab.tsx
  src/app/(main)/gatherings/[id]/reviews/_component/ReviewAverage.tsx
  src/app/(main)/gatherings/create/_component/AddressInput.test.tsx
  src/app/(main)/gatherings/create/_component/FormOnlineAddress.test.tsx
  src/app/(main)/gatherings/create/_component/GatheringForm.tsx
  src/app/(main)/gatherings/create/_component/GatheringUploadImage.test.tsx
  src/app/(main)/gatherings/create/_component/SubCategoryButton.test.tsx
  src/app/(main)/gatherings/create/_component/SubCategoryButton.tsx
  src/app/(main)/gatherings/create/page.tsx
  src/app/(main)/gatherings/edit/_component/GatheringEdit.tsx
  src/app/(main)/mypage/_components/MypageTabs.tsx
  src/app/(main)/mypage/_components/ProfileBox.tsx
  src/app/(main)/mypage/_components/UpperPart.tsx
  src/app/(main)/mypage/_components/skeletons/MyPageProfileBoxSkeleton.tsx
  src/app/(main)/mypage/gatherings/page.tsx
  src/app/(main)/mypage/layout.tsx
  src/app/(main)/mypage/reviews/page.tsx
  src/app/(main)/mypage/schedules/page.tsx
  src/components/common/ProgressBar.tsx
  src/components/common/Tabs.tsx
  src/components/common/Tags.tsx
  src/components/common/cards/MoimCard.tsx
  src/components/common/editor/Tiptab.tsx
  src/components/common/modal/Modal.tsx
  src/constants/scoreMapping.ts
  src/middleware.ts
  src/queries/gatherings-workspace/useGatheringCreate.ts
  src/queries/gatherings-workspace/useGatheringDelete.ts
  src/queries/gatherings-workspace/useGatheringPatch.ts
  src/queries/mypage/useGathering.ts
  src/queries/mypage/useReview.ts
  src/queries/mypage/useSchedule.ts
  src/schemas/gatheringCreate.ts
Labels: 💻 deploy

#76 docs: update readme
  README.md
Labels: 📝 docs

#77 docs: update readme
  README.md
Labels: 📝 docs

#81 chore: s3 버킷 변경 도메인 추가
  next.config.js
  src/queries/gatherings/useGatheringJoin.ts
  src/queries/gatherings/useGatheringJoinCancel.ts
Labels: ⚙️ setting, 🛠️ refactor

#78 deploy: readme main 병합
  README.md
  next.config.js
  src/queries/gatherings/useGatheringJoin.ts
  src/queries/gatherings/useGatheringJoinCancel.ts
Labels: 📝 docs, 💻 deploy

#82 docs: update readme
  README.md
Labels: 📝 docs

#83 fix: 이미지 콘솔 경고 수정
  next.config.js
  src/app/(main)/gatherings/[id]/_component/DetailCardMember.tsx
  src/app/(main)/gatherings/[id]/_component/MemberModal.tsx
  src/app/(main)/gatherings/[id]/layout.tsx
  src/app/(main)/gatherings/create/_component/AddressInput.tsx
  src/app/(main)/gatherings/create/_component/GatheringUploadImage.tsx
  src/app/(main)/mypage/_components/ProfileBox.tsx
  src/app/(main)/mypage/_components/ProfileEdit.tsx
  src/app/(main)/mypage/_components/ScheduleCard.tsx
  src/app/(main)/mypage/_components/UnreviewedCard.tsx
  src/app/_component/BackButton.tsx
  src/components/common/cards/DetailCard.tsx
  src/components/common/cards/MoimCard.tsx
  src/components/common/editor/Tiptab.tsx
  src/components/common/editor/TiptabImage.tsx
  src/components/common/editor/TiptabLink.tsx
  src/components/common/editor/Toolbar.tsx
Labels: 🛠️ refactor
